### ISSUE TITLE
Добавить аннотацию к описанию

### ISSUE THREAD

**Issue by eldario** [opiy-org/yookassa-sdk-php#1]
Добавьте, пожалуйста, описание к этому репозиторию.

Что это форк, сделано для того чтобы получить доступ к временно ушедшему пакету.

Спасибо

**Comment by opiy-org** [comment]
[#e6b427a1c50568182ad878f34dda1f4edaaa60af](https://github.com/opiy-org/yookassa-sdk-php/commit/e6b427a1c50568182ad878f34dda1f4edaaa60af)
